### ISSUE TITLE
Part 1 nit-picking

### ISSUE THREAD

**Issue by marqur09** [tyrantkhan/transport-survey#18]
On the "Survey Part 1: What to Expect" page, remove the second colon on Setting the delivery scene::
Same page, Further -> Farther for option A

Next page, the sample Q should be ($25,100) and ($15,blank)
Same page, the labels for A and B are leftover from before...let's make it:
A: Farther away, lower fine
B: At location, higher fine
-> this appears to be an issue for all of Part 1, not just the sample

Next page, the begin the survey, again to change Further to Farther

**Comment by tyrantkhan** [comment]
done
