### ISSUE TITLE
Part 2 nit-picking; and Part 3

### ISSUE THREAD

**Issue by marqur09** [tyrantkhan/transport-survey#20]
Sample Q: use (300,75) vs 125

Q17 should be all negative values but my input y6 is coming up positive for some values of P? Either the thing is being insane and jumping back and forth plus minus or I am reeeallly drunk...
Yeah, I just checked and Q19 was doing the same weirdness; looks like it starts at negative and then as soon as anything is entered in the box, it jumps to positive.

Part 3: There is an extra open response box under education level that was probably left from before when it was open, but now it is select one.

**Comment by tyrantkhan** [comment]
very good drunk catch!
